//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nivaes.DataTestGenerator.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nivaes.DataTestGenerator.Resources.ResourceNames", typeof(ResourceNames).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antonio;0.020255577
        ///José;0.018558848
        ///Manuel;0.017443977
        ///Francisco;0.015107846
        ///Juan;0.010451432
        ///David;0.009531853
        ///José Antonio;0.008648015
        ///José Luis;0.008337209
        ///Javier;0.008053451
        ///Jesús;0.007883004
        ///Francisco Javier;0.007818463
        ///Carlos;0.007533683
        ///Daniel;0.007478912
        ///Miguel;0.007031436
        ///Rafael;0.006778092
        ///José Manuel;0.006722998
        ///Pedro;0.006636118
        ///Alejandro;0.006484134
        ///Ángel;0.006281873
        ///Miguel Ángel;0.006179653
        ///José María;0.006018328
        ///Fernando;0.00580253
        ///Luis;0.005688144
        ///Pablo;0.005354381
        ///S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to García;0.049374729
        ///Gonzalez;0.031120748
        ///Rodríguez;0.031050686
        ///Fernández;0.03086875
        ///López;0.029263744
        ///Martínez;0.027998989
        ///Sánchez;0.027393747
        ///Pérez;0.02614918
        ///Gómez;0.016497489
        ///Martín;0.016435488
        ///Jiménez;0.013060232
        ///Ruiz;0.012313465
        ///Hernández;0.011984441
        ///Díaz;0.011347016
        ///Moreno;0.010660585
        ///Alvarez;0.009495009
        ///Muñoz;0.009436175
        ///Romero;0.007337332
        ///Alonso;0.006660596
        ///Gutiérrez;0.006518206
        ///Navarro;0.005956206
        ///Torres;0.005633313
        ///Domínguez;0.005290064
        ///Vázquez;0.004967237
        ///Ramos;0.004833875
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
    }
}
