name: Delete old workflow runs

on:
  schedule:
    - cron: "7 3 * * 0"   # Todos los domingos a las 03:07 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    uses: Nivaes/Nivaes.Workflows/.github/workflows/delete-old-runs.yaml@develop  
