name: Delete old workflow runs of deleted branch

on:
  delete:
    branches:
      - '**'   # se activa al borrar cualquier rama

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete runs from the deleted branch
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.event.ref }}   # SOLO la rama borrada
          keep_minimum_runs: 0
          retain_days: 0
