name: Publish Release

on:
  release:
    types:
      - released
      - prereleased

permissions:
  contents: read

jobs:
  publish_release:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Release
      run: |
        echo "Tag: ${{ github.event.release.tag_name }}"

    - name: Download attach assets 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release download "${{ github.event.release.tag_name }}" --dir ./Artifacts
       
    - name: Show downloaded files
      run: ls -lh ./Artifacts

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5   

    - name: Publish packages
      run: dotnet nuget push ./Artifacts/*.nupkg --skip-duplicate --source nuget.org --api-key ${{ secrets.NIVAES_NUGET_TOKEN }}
